hyperskill_project:
  id: 354
  ide_files: https://cogniterra.org/media/attachments/lesson/27800/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Wed, 12 Jul 2023 16:48:59 UTC"
stages:
- id: 2075
  step: 29144
  is_completed: true
- id: 2076
  step: 29145
  is_completed: true
- id: 2077
  step: 29146
  is_completed: true
- id: 2078
  step: 29147
  is_completed: true
- id: 2079
  step: 29148
  is_completed: true
- id: 2080
  step: 29149
  is_completed: true
topics:
  0:
  - title: Computer algorithms
    theory_id: 16547
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Intro to Machine Learning
    theory_id: 10403
  - title: Typical ML pipeline
    theory_id: 10411
  - title: Introduction to regression
    theory_id: 11417
  - title: Introduction to classification
    theory_id: 10942
  - title: Computer programming
    theory_id: 8739
  - title: Paradigms
    theory_id: 15860
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Load module
    theory_id: 6019
  - title: Create module
    theory_id: 6057
  - title: Packages
    theory_id: 6384
  - title: Introduction to OOP
    theory_id: 3614
  - title: Taking input
    theory_id: 5913
  - title: Naming variables
    theory_id: 5885
  - title: Pip
    theory_id: 6230
  - title: Virtual Environment
    theory_id: 13923
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Class
    theory_id: 6661
  - title: Class instances
    theory_id: 6669
  - title: For loop
    theory_id: 6065
  - title: While loop
    theory_id: 5940
  - title: Loop control statements
    theory_id: 6302
  - title: The Jupyter Notebook
    theory_id: 12623
  - title: Google Colab
    theory_id: 12631
  - title: Methods
    theory_id: 6931
  - title: Methods and attributes
    theory_id: 6981
  - title: PyCharm basics
    theory_id: 6193
  - title: Sep and end arguments of print
    theory_id: 7452
  - title: Introduction to pandas
    theory_id: 10416
  - title: Introduction to sklearn
    theory_id: 10430
  - title: Training a model with sklearn
    theory_id: 14678
  - title: Decision Trees
    theory_id: 11426
  - title: Decision tree with sklearn
    theory_id: 16405
  - title: Accuracy and confusion matrix
    theory_id: 11245
  - title: Series
    theory_id: 10421
  - title: DataFrame
    theory_id: 10933
  - title: Train and test sets
    theory_id: 17181
  - title: Basic data types
    theory_id: 5852
  - title: Variables
    theory_id: 5859
  - title: Invoking a function
    theory_id: 5891
  - title: Integer arithmetic
    theory_id: 5865
  - title: Declaring a function
    theory_id: 5900
  - title: Scopes
    theory_id: 6322
  - title: List
    theory_id: 5979
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: String formatting
    theory_id: 6037
  - title: Arguments
    theory_id: 7248
  - title: Basic string methods
    theory_id: 6842
  - title: Type casting
    theory_id: 6224
  - title: Escape sequences
    theory_id: 7130
  - title: Split and join
    theory_id: 6972
  - title: Dictionary
    theory_id: 6481
  2:
  - title: Ensemble methods
    theory_id: 15391
  - title: Random forest
    theory_id: 16554
  5:
  - title: Cartesian coordinates
    theory_id: 13114
  - title: "Vectors, matrices, scalars"
    theory_id: 16969
  - title: Introduction to matrices
    theory_id: 7112
  - title: Intro to NumPy
    theory_id: 9672
  - title: Introduction to matplotlib
    theory_id: 16788
  - title: Matplotlib scatter plot
    theory_id: 17926
